stages:
  - build
  - publish

variables:
  GATEWAY_IMAGE_NAME: "mmb-gateway"
  CLIENT_IMAGE_NAME: "mmb-client"

publish-gateway-latest:
    stage: publish
    #when: manual
    image: docker:latest
    services:
      - docker:dind
    only:
      - staging
      - ci-latest
    script:
      - CONTAINER_IMAGE=$(echo "$CI_REGISTRY/$CI_PROJECT_PATH/$GATEWAY_IMAGE_NAME" | tr '[A-Z]' '[a-z]')
      - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
      - docker pull $CONTAINER_IMAGE:latest || true
      - DOCKER_BUILDKIT=1 docker build -f docker/scripts/gateway/Dockerfile --cache-from $CONTAINER_IMAGE:latest -t $GATEWAY_IMAGE_NAME .
      - docker tag $GATEWAY_IMAGE_NAME $CONTAINER_IMAGE:latest
      - docker push $CONTAINER_IMAGE:latest
      - docker logout

publish-client-latest:
    stage: publish
    #when: manual
    image: docker:latest
    services:
      - docker:dind
    only:
      - staging
      - ci-latest
    script:
      - CONTAINER_IMAGE=$(echo "$CI_REGISTRY/$CI_PROJECT_PATH/$CLIENT_IMAGE_NAME" | tr '[A-Z]' '[a-z]')
      - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
      - docker pull $CONTAINER_IMAGE:latest || true
      - DOCKER_BUILDKIT=1 docker build -f docker/scripts/client/Dockerfile --cache-from $CONTAINER_IMAGE:latest -t $CLIENT_IMAGE_NAME .
      - docker tag $CLIENT_IMAGE_NAME $CONTAINER_IMAGE:latest
      - docker push $CONTAINER_IMAGE:latest
      - docker logout

publish-gateway:
    stage: publish
    #when: manual
    image: docker:latest
    services:
      - docker:dind
    only:
      - production
      - ci-stable
      - master
      - main
    script:
      - CONTAINER_IMAGE=$(echo "$CI_REGISTRY/$CI_PROJECT_PATH/$GATEWAY_IMAGE_NAME" | tr '[A-Z]' '[a-z]')
      - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
      - docker pull $CONTAINER_IMAGE:stable || true
      - DOCKER_BUILDKIT=1 docker build -f docker/scripts/gateway/Dockerfile --cache-from $CONTAINER_IMAGE:stable -t $GATEWAY_IMAGE_NAME .
      - docker tag $GATEWAY_IMAGE_NAME $CONTAINER_IMAGE:stable
      - docker push $CONTAINER_IMAGE:stable
      - docker logout

publish-client:
    stage: publish
    #when: manual
    image: docker:latest
    services:
      - docker:dind
    only:
      - production
      - ci-stable
      - master
      - main
    script:
      - CONTAINER_IMAGE=$(echo "$CI_REGISTRY/$CI_PROJECT_PATH/$CLIENT_IMAGE_NAME" | tr '[A-Z]' '[a-z]')
      - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
      - docker pull $CONTAINER_IMAGE:stable || true
      - DOCKER_BUILDKIT=1 docker build -f docker/scripts/client/Dockerfile --cache-from $CONTAINER_IMAGE:stable -t $CLIENT_IMAGE_NAME .
      - docker tag $CLIENT_IMAGE_NAME $CONTAINER_IMAGE:stable
      - docker push $CONTAINER_IMAGE:stable
      - docker logout